[package]
name = "linguaporta-automation"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.12.0"
dotenv = "0.15.0"
thirtyfour = "0.36.1"
tokio = { version = "1.47.1", features = ["full"]}
